<a href="https://colab.research.google.com/github/scarlett-plaza/Clase2/blob/master/fase1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#!pip install astroquery 
import astropy.units as u
from astropy.coordinates import SkyCoord
from astroquery.gaia import Gaia
from astroquery.sdss import SDSS
import pandas as pd
from astropy.io import fits
from astropy.wcs import WCS
from astropy.utils.data import download_file

In [7]:
import warnings
warnings.filterwarnings("ignore", module='astropy.io.votable.tree')
archivo = download_file('https://github.com/astrodatos/Clase3/raw/master/planets.csv')
data = pd.read_csv(archivo,comment='#')
ra=data['ra']
dec=data['dec']

job = Gaia.launch_job_async("select top 10000 \
solution_id,random_index,source_id,ra,dec,phot_g_mean_mag,phot_bp_mean_mag,phot_rp_mean_mag,bp_rp,bp_g,g_rp,teff_val,lum_val \
from gaiadr2.gaia_source order by random_index") #obtenemos los datos de 1000000 estrellas con los anteriores atributos en un Asynchronous query

Downloading https://github.com/astrodatos/Clase3/raw/master/planets.csv [Done]
Query finished.

In [9]:
print(job) 
r = job.get_results()
results=r.to_pandas()

<Table masked=True length=10000>
      name        dtype  unit format                            description                             n_bad
---------------- ------- ---- ------ ------------------------------------------------------------------ -----
     solution_id   int64                                                            Solution Identifier     0
    random_index   int64                                            Random index used to select subsets     0
       source_id   int64             Unique source identifier (unique within a particular Data Release)     0
              ra float64  deg {!r:>}                                                    Right ascension     0
             dec float64  deg {!r:>}                                                        Declination     0
 phot_g_mean_mag float32  mag {!r:>}                                              G-band mean magnitude     0
phot_bp_mean_mag float32  mag {!r:>}                                       Integrated BP mean magnitude  1849
phot_rp_mean_mag float32  mag {!r:>}                                       Integrated RP mean magnitude  1840
           bp_rp float32  mag {!r:>}                                                     BP - RP colour  1862
            bp_g float32  mag {!r:>}                                                      BP - G colour  1849
            g_rp float32  mag {!r:>}                                                      G - RP colour  1840
        teff_val float32    K {!r:>}                                      stellar effective temperature  9071
         lum_val float32 Lsun {!r:>}                                                 stellar luminosity  9559
Jobid: 1559746480095O
Phase: COMPLETED
Owner: None
Output file: async_20190605145440.vot
Results: None

In [11]:
results

              solution_id  random_index  ...     teff_val   lum_val
0     1635721458409799680             0  ...          NaN       NaN
1     1635721458409799680             1  ...          NaN       NaN
2     1635721458409799680             2  ...          NaN       NaN
3     1635721458409799680             3  ...          NaN       NaN
4     1635721458409799680             4  ...          NaN       NaN
5     1635721458409799680             5  ...          NaN       NaN
6     1635721458409799680             6  ...          NaN       NaN
7     1635721458409799680             7  ...          NaN       NaN
8     1635721458409799680             8  ...  4368.459961       NaN
9     1635721458409799680             9  ...          NaN       NaN
10    1635721458409799680            10  ...          NaN       NaN
11    1635721458409799680            11  ...          NaN       NaN
12    1635721458409799680            12  ...  5070.041992       NaN
13    1635721458409799680            13  ...          NaN       NaN
14    1635721458409799680            14  ...          NaN       NaN
15    1635721458409799680            15  ...          NaN       NaN
16    1635721458409799680            16  ...          NaN       NaN
17    1635721458409799680            17  ...  4361.000000       NaN
18    1635721458409799680            18  ...          NaN       NaN
19    1635721458409799680            19  ...          NaN       NaN
20    1635721458409799680            20  ...          NaN       NaN
21    1635721458409799680            21  ...  4919.000000  0.704140
22    1635721458409799680            22  ...          NaN       NaN
23    1635721458409799680            23  ...          NaN       NaN
24    1635721458409799680            24  ...  5364.750000       NaN
25    1635721458409799680            25  ...          NaN       NaN
26    1635721458409799680            26  ...          NaN       NaN
27    1635721458409799680            27  ...          NaN       NaN
28    1635721458409799680            28  ...          NaN       NaN
29    1635721458409799680            29  ...  3610.000000       NaN
...                   ...           ...  ...          ...       ...
9970  1635721458409799680          9970  ...          NaN       NaN
9971  1635721458409799680          9971  ...          NaN       NaN
9972  1635721458409799680          9972  ...          NaN       NaN
9973  1635721458409799680          9973  ...          NaN       NaN
9974  1635721458409799680          9974  ...          NaN       NaN
9975  1635721458409799680          9975  ...          NaN       NaN
9976  1635721458409799680          9976  ...          NaN       NaN
9977  1635721458409799680          9977  ...          NaN       NaN
9978  1635721458409799680          9978  ...          NaN       NaN
9979  1635721458409799680          9979  ...          NaN       NaN
9980  1635721458409799680          9980  ...          NaN       NaN
9981  1635721458409799680          9981  ...          NaN       NaN
9982  1635721458409799680          9982  ...          NaN       NaN
9983  1635721458409799680          9983  ...  4737.000000       NaN
9984  1635721458409799680          9984  ...          NaN       NaN
9985  1635721458409799680          9985  ...          NaN       NaN
9986  1635721458409799680          9986  ...          NaN       NaN
9987  1635721458409799680          9987  ...  5358.000000  6.436867
9988  1635721458409799680          9988  ...          NaN       NaN
9989  1635721458409799680          9989  ...          NaN       NaN
9990  1635721458409799680          9990  ...          NaN       NaN
9991  1635721458409799680          9991  ...          NaN       NaN
9992  1635721458409799680          9992  ...          NaN       NaN
9993  1635721458409799680          9993  ...          NaN       NaN
9994  1635721458409799680          9994  ...          NaN       NaN
9995  1635721458409799680          9995  ...          NaN       NaN
9996  1635721458409799680          9996  ...          NaN       NaN
9997  1635721458409799680          9997  ...          NaN       NaN
9998  1635721458409799680          9998  ...          NaN       NaN
9999  1635721458409799680          9999  ...          NaN       NaN

[10000 rows x 13 columns]